### ISSUE TITLE
改进更新集市包的发布流程

### ISSUE THREAD

**Issue by 88250** [siyuan-note/bazaar#1061]
目前如果要更新集市发布包的话需要集市仓库作者手动 PR commit hash，这个流程较为繁琐，改进为作者在 GitHub 上创建 Release 即可，集市服务器会通过 GitHub Actions 定时自动拉取 latest release 进行索引。

请注意：

* 这是仅针对更新集市包的改进，如果是初次上架集市，仍然需要 PR 仓库地址
* 之前如果没有创建过 Release 的话需要创建一下，否则无法上架成功

**Comment by terwer** [comment]
大赞！！！
