### ISSUE TITLE
集市中抓取的发布时间与版本不符

### ISSUE THREAD

**Issue by tcmtom** [siyuan-note/bazaar#1073]
![image](https://user-images.githubusercontent.com/94541098/206623492-fe0c9938-4989-4b9c-bfff-e236b1e46e51.png)
[release地址](https://github.com/Achuan-2/siyuan-themes-tsundoku-green/releases)
机器人好像是只抓取到了更新的时间，没有抓取到更新后的版本

**Comment by 88250** [comment]
https://github.com/Achuan-2/siyuan-themes-tsundoku-green/blob/main/theme.json 这个文件没有改版本号哦。
