### ISSUE TITLE
插件集市更新没有触发

### ISSUE THREAD

**Issue by l1422586361** [siyuan-note/bazaar#1076]
大佬，集市更新机制改版后，我后面的更新除了改版后的第一个版本正常更新后，后面的版本都没有同步更新到集市，都是已经按说明修改了widgets.json和创建release，目前我对比其他有发版成功的项目，没有找到有区别，希望可以麻烦您看一下

插件仓库release链接：https://github.com/l1422586361/widget-graph/releases/tag/2.0.1

**Comment by 88250** [comment]
需要等待部署社区集市服务器，今天发版 SiYuan 后部署，谢谢。

**Comment by l1422586361** [comment]
我的是从12月份后就没有同步更新到集市了o(╥﹏╥)o，所以就是想看看有没有哪里是有问题

**Comment by 88250** [comment]
你看下这个自动生成的索引文件是否对应你那边正常的 hash https://github.com/siyuan-note/bazaar/blob/main/stage/widgets.json

**Comment by l1422586361** [comment]
这个是对应的，更新时间也对得上




红尘嚣,浮华一世转瞬空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/bazaar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/bazaar] 插件集市更新没有触发 (Issue #1076)





 
你看下这个自动生成的索引文件是否对应你那边正常的 hash https://github.com/siyuan-note/bazaar/blob/main/stage/widgets.json

**Comment by 88250** [comment]
等发版部署以后看看吧，还有问题回复我。
