### ISSUE TITLE
逐步下架不使用 package.zip 发布的包

### ISSUE THREAD

**Issue by 88250** [siyuan-note/bazaar#1105]

**Comment by 88250** [comment]
## Widget

* Achuan-2/siyuan-widget-clockpac
* macvip/widget-cover-drawio
* InEase/SiYuan-Xmind
* langzhou/note-backlinks
* langzhou/note-attrs
* langzhou/note-views-v3
* leolee9086/cc-sy-luckysheet
* leolee9086/cc-template
* leolee9086/cc-image-tag-new
* langyamu/siyuan-calendar
* weihan-Chen/WordCounter
* Azer-Zem/TextReader
* TheGodOfKing/Notetocard-siyuan
* leolee9086/cc-kityminder
* iamqiz/siyuan-widget-doc-merge
* iamqiz/learn-siyuan-widget
* Zuoqiu-Yingyi/widget-pseudocode
* winter60/Embed-Pagination
* zuoez02/sy-mathjax
* zuoez02/sy-excalidraw
* eulores/siyuan-brython-run
* mohuishou/siyuan-sync-github
* dicarne/sy-secret-block
* dicarne/sy-canvas
* fatevase/SiYuanDailyViews
* l1422586361/widget-graph
* hamsterbase/siyuan-hamsterbase
* Zuoqiu-Yingyi/widget-brython-editor
* Zuoqiu-Yingyi/widget-brython-console

**Comment by 88250** [comment]
## Theme

* mindstudy/siyuan-themes-concise-light
* mindstudy/siyuan-themes-concise-dark
* Oltermare/Ori-Light-for-Mobile
* Oltermare/Ori-Dark-for-Mobile
* OIREVASMAI/Oir-Light
* weihan-Chen/pureDark
* weihan-Chen/CityInDark
* Soltus/BHQ-Mobile
* UserZYF/blue-dog
* lanedu/Knowledge-Brain
* Oltermare/Consistent

**Comment by Aiviokoo** [comment]
规范是好事（支持D大），看这条issues也有1个月了，给绝大多数社区开发者的时间应该也算很足的。
这里想贴上自己刚刚在群里发表的一些话吧（仅个人所言，可能考虑不太周到）
![image](https://github.com/siyuan-note/bazaar/assets/87182333/675b9369-9fb4-4345-ba20-2737ea78febf)

**Comment by 88250** [comment]
## Icon

* https://github.com/royc01/notion-icon
* https://github.com/materium/siyuan-icon

**Comment by 88250** [comment]
## Template

* https://github.com/zhangzz66/MeteorDiary
* https://github.com/zhangzz66/list-find
* https://github.com/svchord/siyuan-template-NotionCover
* https://github.com/Crowds21/Organized
* https://github.com/lanedu/Me
* https://github.com/shawnblues/normal
* https://github.com/idea-zone/BWLabels
* https://github.com/idea-zone/ZCard

**Comment by 88250** [comment]
## Theme

* https://github.com/UFDXD/HBuilderX-Light

**Comment by 88250** [comment]
## Widget

* https://github.com/suka233/siyuan-calendiary
* https://github.com/suka233/siyuan-Kmind
* https://github.com/Zuoqiu-Yingyi/widget-metadata
* https://github.com/Blackman99/siyuan-plugin-react-repl
* https://github.com/LinuaBio/GeogebraE
* https://github.com/KarlKaijie/SiYuanToDo
* https://github.com/Blackman99/siyuan-plugin-svelte-repl
* https://github.com/BryceAndJuly/Document-Timeline
