### ISSUE TITLE
挂件更新后无法从集市中找到了

### ISSUE THREAD

**Issue by ooooooook** [siyuan-note/bazaar#1147]
如题，自己弄的挂件从v0.0.3升到v0.0.4后在思源集市中就找不到了。不知道哪里有问题？请问从哪里获取上架失败的原因？

挂件仓库地址：https://github.com/ooooooook/widget-excalidraw

**Comment by 88250** [comment]
https://github.com/ooooooook/widget-excalidraw/tree/c503e96b20a9006717ed34f184e50cd481bc8126

这个版本里面没有 widget.json ，建议重新发布一个新版本。
