### ISSUE TITLE
一键多选笔记

### ISSUE THREAD

**Issue by luckysmithlee** [siyuan-note/bazaar#1215]
我想使用像在浏览器中选择文字一样使用shift键一次选择多个笔记，但实际效果是在右侧打开了新的标签页，使用command键是可以一个一个选中实现多选的，但这样效率很低，尝试shift+command和option+command均无果，请问目前是支持的吗？如果不支持希望在后期可以支持

**Comment by 88250** [comment]
不支持，Shift+Click 是分屏打开。

另外，你提 issue 没有选对仓库，应该是这个 https://github.com/siyuan-note/siyuan

**Comment by luckysmithlee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到你的邮件。
