### ISSUE TITLE
插件更新错误，RogerHuHu/siyuan-plugin-schedule-manager

### ISSUE THREAD

**Issue by RogerHuHu** [siyuan-note/bazaar#1256]
![errorlog](https://github.com/siyuan-note/bazaar/assets/3404169/fae80b62-52fc-48cd-b3b2-b3ed105093fc)
在集市可以看到更新，在已安装插件列表处无法看到更新

**Comment by 88250** [comment]
请看下是不是没有按照规范打包文件。

**Comment by RogerHuHu** [comment]
![package](https://github.com/siyuan-note/bazaar/assets/3404169/9db178d9-895e-4bfd-8da0-666bc9c82f7e)
包内容是这样的

**Comment by 88250** [comment]
我刚刚重现运行了一次 action，没有 stat 相关报错了。可以等后面自动运行 action 后再看看，先睡了，晚安。

**Comment by RogerHuHu** [comment]
对了，是更新版本后的第一次运行Action会报这个错，后面就不会，但是这也导致了已安装插件列表没法看到更新

**Comment by 88250** [comment]
暂时不太清楚问题原因，我看其他插件好像是正常的。这样吧，我这里刚刚安装了 v1.0.8，你有空的话只改一个版本号后发版 release，我们再测测看能不能重现问题。

**Comment by RogerHuHu** [comment]
我现在操作一下

**Comment by RogerHuHu** [comment]
已经发布了
![image](https://github.com/siyuan-note/bazaar/assets/3404169/93cf033d-d247-4f05-9f6d-210d2eea59f7)

**Comment by 88250** [comment]
好的，我们等下一轮 action 跑完看看日志。

**Comment by 88250** [comment]
action 日志中的警告是正常的，是用于说明 cdn 上没有该文件，需要上传文件。

我这里在已安装插件页签中可以看到更新按钮：

![image](https://github.com/siyuan-note/bazaar/assets/873584/f4446303-4752-44e1-87fa-c02190735b83)

点击后可以正常更新。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
