### ISSUE TITLE
在集市可以看到更新，在已安装插件列表处无法看到更新

### ISSUE THREAD

**Issue by shenjinglei** [siyuan-note/bazaar#1264]
## 遇到的问题

我在发布“关系图增强”插件新版本后，在集市可以看到更新，在已安装插件列表处无法看到更新。在集市安装后无其他异常。
![image](https://github.com/siyuan-note/bazaar/assets/11613616/dd90061f-290f-469b-b2e1-5e757b04d997)
![image](https://github.com/siyuan-note/bazaar/assets/11613616/21e33123-edb1-4c5f-9783-f96595e43801)

## 可能的推测

我在之前有一次发布的时候，错把plugin.json中的版本号加上了“v”类似“v0.1.4”。虽然之后能正常更新，但好像从那时起就出现这种情况了。不知道是不是这样造成的。

**Comment by 88250** [comment]
这个可能需要重新安装才能确定了，因为链路有点长，检查起来有点费劲，所以还是麻烦你通过卸载重装，然后更新发布新版本后再帮忙确认一下，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by shenjinglei** [comment]
我重新在虚拟机中安装了全新的思源。安装“关系图增强”插件v0.2.0。然后发布v0.2.1，能复现该问题。在IPAD端，也能复现该问题。🙏

**Comment by 88250** [comment]
定位到问题了，是因为 plugin.json 里面多了个空格：

![image](https://github.com/siyuan-note/bazaar/assets/873584/09cb9b8d-84dc-47ac-b7dd-8556fd8649d6)

**Comment by shenjinglei** [comment]
谢谢。下次我更新的时候修正下。
