### ISSUE TITLE
模板集市上架异常

### ISSUE THREAD

**Issue by Crowds21** [siyuan-note/bazaar#133]
模板地址: https://github.com/Crowds21/Organized

```
"Crowds21/Organized@1f4d9a58a12405762da72eff15994eba214cc741",
```
昨天下午上传完毕,到现在为止还没有正常显示.

![image](https://user-images.githubusercontent.com/48215334/126860090-df8b0de1-65d9-46dc-b839-672edf386c7e.png)

**Comment by 88250** [comment]
这个需要人工部署，稍后就部署，谢谢。

**Comment by Crowds21** [comment]
> 这个需要人工部署，稍后就部署，谢谢。

一直以为是自动的.
哈哈哈哈,明白了,周末Ｄ大放假，下次等工作日一起传，不催了.

**Comment by 88250** [comment]
周末愉快，刚刚部署好了 😂
