### ISSUE TITLE
内容再粘回文档无法高亮

### ISSUE THREAD

**Issue by tongzi001** [siyuan-note/bazaar#1371]
搜索完文档，然后剪切全部内容再粘贴回文档，此时再次点击上下搜索键，就只有个数字再跳动了不显示高亮。
![d51ec7fc3530ecf61a601a1af1c443c0_screenshots-QGUOZQK](https://github.com/siyuan-note/bazaar/assets/148167517/e2f3fd55-346a-4741-8d5f-083193fa26c5)

**Comment by 88250** [comment]
你好，请不要在社区集市仓库上提，请到对应的插件仓库上提。

**Comment by tongzi001** [comment]
看错了 还以为这是高亮插件的issue
