### ISSUE TITLE
重复搜索再次粘贴回的内容无法高亮

### ISSUE THREAD

**Issue by tongzi001** [siyuan-note/bazaar#1372]
搜索完这个文档关键字后，然后全部剪切文档内容，再次粘贴回文档。此时再次搜索，就只有个数字了然后不显示高亮。
![d51ec7fc3530ecf61a601a1af1c443c0_screenshots-QGUOZQK](https://github.com/siyuan-note/bazaar/assets/148167517/5e8bcc24-59b5-4034-840a-b699e58a3ed3)

**Comment by 88250** [comment]
你好，请不要在社区集市仓库上提，请到对应的插件仓库上提。
