### ISSUE TITLE
有插件在集市里丢失了

### ISSUE THREAD

**Issue by tengfei-xy** [siyuan-note/bazaar#1481]
插件名称：siyuan-plugin-share-system
我更新到插件[2.3.1](https://github.com/tengfei-xy/siyuan-plugin-share-system/releases/tag/v2.3.1)版本，集市里没有这个插件，但[bazaar/plugins.json](https://github.com/siyuan-note/bazaar/tree/main)里还有我的这个插件。

**Comment by tengfei-xy** [comment]
麻烦有空处理下哈～谢谢

**Comment by 88250** [comment]
可以在 Actions 构建中看，目前是报错状态：

![image](https://github.com/user-attachments/assets/ebed2044-ee47-4274-a5e6-a56ef3427bc4)

因为 Release 里你没有上传 package.zip：

![image](https://github.com/user-attachments/assets/fad51df0-ea57-4e3b-ab44-0e0d5364f780)

上传完后等几个小时 action 自动重新运行应该就能看到了。

**Comment by tengfei-xy** [comment]
了解了，感谢～
