### ISSUE TITLE
从基于 `commit` 的版本改为基于 `release` 的版本

### ISSUE THREAD

**Issue by kecrily** [siyuan-note/bazaar#157]
现在所采用的通过作者手动更新至 commit 的 hash 值来进行更新过于烦琐，可以考虑改用 obsidian 一样的自动获得该仓库最新发布的 release。

**Comment by 88250** [comment]
考虑过用 release 的，但是如果有个小改动就要发布一次有点不大好……还是用 commit hash 比较灵活，我关闭了哦。
