### ISSUE TITLE
下架一些过时的主题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/bazaar#60]
@ihyw @yuuuxt 两位谁空请帮忙处理一下，谢谢。

**Comment by ihyw** [comment]
![image](https://user-images.githubusercontent.com/74618439/107176351-15a0a980-6a0a-11eb-97ee-d93b6e2c7a57.png)
感觉有一部分用户依然在使用那些主题，直接下架不知道会不会有点突兀

**Comment by ihyw** [comment]
或许有时间弄的话，可以加个小标记啥的，让用户自行选择，直接下架感觉有的喜欢那些主题某些特性的用户就突然用不上了

**Comment by 88250** [comment]
是个好主意，等后面完善下。
